sgp/urls.py
from django.contrib import admin
from django.urls import path
from sgpapp.views import index, gerenciar, cadastro, lista_servidores, editar_servidor, apagar_servidor, detalhar_servidor

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name='index'),
    path('gerenciar/', gerenciar, name='gerenciar'),
    path('cadastro/', cadastro, name='cadastro'),
    path('lista_servidores/', lista_servidores, name='lista_servidores'),
    path('editar_servidor/<int:servidor_id>/', editar_servidor, name='editar_servidor'),
    path('apagar_servidor/<int:servidor_id>/', apagar_servidor, name='apagar_servidor'),
    path('servidor/<int:id>/', detalhar_servidor, name='detalhar_servidor'),


]

sgpapp/models.py
from django.db import models


class Cadastro(models.Model):
    # Informações Pessoais
    SEXO_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    nome = models.CharField(max_length=100)
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES)
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()
    data_nascimento = models.DateField(null=True, blank=True)

    ZONA_CHOICES = (
        ('U', 'Zona Urbana'),
        ('R', 'Zona Rural'),
    )
    # Endereço
    logradouro = models.CharField(max_length=100, blank=True)
    numero = models.CharField(max_length=10, blank=True)
    zona = models.CharField(max_length=10, choices=ZONA_CHOICES)
    bairro = models.CharField(max_length=50, blank=True)
    estado = models.CharField(max_length=50, blank=True)
    municipio = models.CharField(max_length=50, blank=True)
    cep = models.CharField(max_length=9, blank=True)

    # Formação
    ESCOLADIRDADE_CHOICES = (
        ('F', 'Ensino Fundamental'),
        ('M', 'Ensino Médio'),
        ('S', 'Ensino Superior'),
    )
    escolaridade = models.CharField(max_length=10, choices=ESCOLADIRDADE_CHOICES)
    formacao = models.CharField(max_length=100, default='', blank=True)
    instituicao = models.CharField(max_length=100, blank=True)

    # Lotação
    LOCAL_CHOICES = (
        ('S', 'SEMED'),
        ('B', 'E.M.E.F Brejo Grande do Araguaia'),
        ('XV', 'E.M.E.F XV de Novembro'),
        ('C', 'E.M.E.F Cilira Vieira'),
        ('F', 'E.M.E.I Felicidade de Brito'),
        ('M', 'E.M.E.I Dona Maria de Nazaré'),
        ('S', 'E.M.E.I.F Silvana Moura'),
        ('J', 'E.M.E.I.F Joventina'),
        ('N', 'E.M.E.I.F Nossa Senhora da Penha'),
        ('SS', 'E.M.E.I.F São José'),
        ('P', 'E.M.E.I.F Padre Cicero'),
        ('SA', 'E.M.E.I.F Sawarapy Suruí'),
        ('D', 'E.M.E.I.F Dom Bosco'),
    )
    VINCULO_CHOICES = (
        ('E', 'Efetivo'),
        ('T', 'Temporário'),
    )
    cargo = models.CharField(max_length=50, blank=True)
    funcao = models.CharField(max_length=50, blank=True)
    vinculo = models.CharField(max_length=15, choices=VINCULO_CHOICES)
    local = models.CharField(max_length=10, choices=LOCAL_CHOICES)

    # Dados Bancários
    banco = models.CharField(max_length=50, blank=True)
    agencia = models.CharField(max_length=10, blank=True)
    conta = models.CharField(max_length=20, blank=True)

    # Informações Adicionais
    data_admissao = models.DateField(null=True, blank=True)
    data_inicio = models.DateField(null=True, blank=True)
    data_saida = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nome

sgpapp/forms.py
from django import forms
from .models import Cadastro


class CadastroForm(forms.ModelForm):
    class Meta:
        model = Cadastro
        fields = '__all__'
        labels = {
            'nome': 'Nome Completo',
            'sexo': 'Sexo',
            'rg': 'RG',
            'cpf': 'CPF',
            'telefone': 'Telefone',
            'email': 'Email',
            'logradouro': 'Logradouro',
            'numero': 'Número',
            'zona': 'Zona',
            'bairro': 'Bairro / Vila',
            'estado': 'Estado',
            'municipio': 'Município',
            'cep': 'CEP',
            'escolaridade': 'Escolaridade',
            'formacao': 'Formação',
            'instituicao': 'Instituição',
            'cargo': 'Cargo',
            'funcao': 'Função',
            'vinculo': 'Vínculo',
            'local': 'Local',
            'banco': 'Banco',
            'agencia': 'Agência',
            'conta': 'Conta',
            'data_admissao': 'Data de Admissão',
            'data_inicio': 'Data de Início',
            'data_saida': 'Data de Saída',
            'data_nascimento': 'Data de Nascimento',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].required = True
        self.fields['sexo'].required = True
        self.fields['rg'].required = True
        self.fields['cpf'].required = True
        self.fields['telefone'].required = True
        self.fields['email'].required = True
        self.fields['zona'].required = False

sgpapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CadastroForm
from .models import Cadastro



def index(request):
    return render(request, 'sgp/index.html')


def gerenciar(request):
    return render(request, 'sgp/gerenciar.html')


def cadastro(request):
    form = CadastroForm()
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            form.save()
            form = CadastroForm()
    return render(request, 'sgp/cadastro.html', {'form': form})


def lista_servidores(request):
    servidores = Cadastro.objects.order_by('nome')  # Ordena os servidores por nome em ordem alfabética
    total_registros = servidores.count()  # Obtém o total de registros

    return render(request, 'sgp/lista_servidores.html', {'servidores': servidores, 'total_registros': total_registros})


def detalhar_servidor(request, id):
    servidor = get_object_or_404(Cadastro, id=id)
    return render(request, 'sgp/detalhar_servidor.html', {'servidor': servidor})

def editar_servidor(request, servidor_id):
    servidor = get_object_or_404(Cadastro, id=servidor_id)
    if request.method == 'POST':
        form = CadastroForm(request.POST, instance=servidor)
        if form.is_valid():
            form.save()
            return redirect('lista_servidores')
    else:
        form = CadastroForm(instance=servidor)
    return render(request, 'sgp/editar_servidor.html', {'form': form})


def apagar_servidor(request, servidor_id):
    servidor = get_object_or_404(Cadastro, id=servidor_id)
    if request.method == 'POST':
        servidor.delete()
        return redirect('lista_servidores')
    return render(request, 'sgp/apagar_servidor.html', {'servidor': servidor})

sgpapp/templates/sgp/apagar_servidor.html
{% extends 'sgp/base.html' %}

{% block content %}
    <h2 class="text-center">Apagar Servidor</h2>
    <div class="container mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border p-4">
                <p>Tem certeza de que deseja apagar o servidor "{{ servidor.nome }}"?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Apagar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sgpapp/templates/sgp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <meta charset="UTF-8">

    <div class="container-fluid">
        <div class="row">
            <div class="container" style="height: 105px;">
                <img height="100" src="/static/img/logo.png" alt="Logo">
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link mx-2 btn rounded-0 btn-danger" aria-current="page"
                           href="http://127.0.0.1:8000/index/">Página
                            Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-2 btn rounded-0 btn-danger" href="http://127.0.0.1:8000/cadastro/">Cadastrar
                            Servidores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-2 btn rounded-0 btn-danger" href="http://127.0.0.1:8000/lista_servidores/">Gerenciar
                            Servidores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-2 btn rounded-0 btn-danger" href="http://127.0.0.1:8000/gerenciarfolha/">Gerenciar
                            Folha</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</head>
<body>
<div class="container">
<br>
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

sgpapp/templates/sgp/cadastro.html
<title>Cadastro de Servidores</title>
{% extends 'sgp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container d-flex justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Informações Pessoais</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group row">
                        <div class="col-md-12">
                            {{ form.nome|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.sexo|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.rg|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            <label for="{{ form.cpf.id_for_label }}">CPF:</label>
                            <input type="text" name="{{ form.cpf.name }}" id="{{ form.cpf.id_for_label }}"
                                   class="form-control" maxlength="14" oninput="formatarCPF(this)" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.telefone|as_crispy_field }}
                        </div>
                        <div class="col-md-8">
                            {{ form.email|as_crispy_field }}
                        </div>
                    <div class="form-group">
                        {{ form.data_nascimento|as_crispy_field }}
                    </div>
                    </div>
                </div>
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Endereço</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group">
                        {{ form.logradouro|as_crispy_field }}
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            {{ form.numero|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.zona|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.cep|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-8">
                            {{ form.municipio|as_crispy_field }}
                        </div>
                        <div class="col-md-4">
                            {{ form.estado|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.bairro|as_crispy_field }}
                    </div>
                </div>
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Formação</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group">
                        {{ form.escolaridade|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.formacao|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.instituicao|as_crispy_field }}
                    </div>
                </div>
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Lotação</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group">
                        {{ form.cargo|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.funcao|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.vinculo|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.local|as_crispy_field }}
                    </div>
                </div>
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Dados Bancários</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group">
                        {{ form.banco|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.agencia|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.conta|as_crispy_field }}
                    </div>
                </div>
                <div class="border border-dark p-2 container text-center bg-dark text-white">
                    <h5>Informações Adicionais</h5>
                </div>
                <div class="border border-dark p-2">
                    <div class="form-group">
                        {{ form.data_admissao|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.data_inicio|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.data_saida|as_crispy_field }}
                    </div>
                </div>
                <div class="text-center mt-4">
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        function formatarCPF(campo) {
            var cpf = campo.value.replace(/\D/g, '');

            if (cpf.length > 3 && cpf.length <= 6)
                cpf = cpf.replace(/^(\d{3})(\d)/, '$1.$2');
            else if (cpf.length > 6 && cpf.length <= 9)
                cpf = cpf.replace(/^(\d{3})(\d{3})(\d)/, '$1.$2.$3');
            else if (cpf.length > 9)
                cpf = cpf.replace(/^(\d{3})(\d{3})(\d{3})(\d)/, '$1.$2.$3-$4');

            campo.value = cpf;
        }
    </script>
{% endblock %}

sgpapp/templates/sgp/detalhar_servidor.html
{% extends 'sgp/base.html' %}

{% block content %}
    <h2 class="text-center">Detalhes do Servidor</h2>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong>Dados Pessoais</strong></h5>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nome"><strong>Nome:</strong> {{ servidor.nome }}</label>
                        </div>
                        <div class="form-group">
                            <label for="sexo"><strong>Sexo:</strong> {{ servidor.get_sexo_display }}</label>
                        </div>
                        <div class="form-group">
                            <label for="rg"><strong>RG:</strong> {{ servidor.rg }}</label>
                        </div>
                        <div class="form-group">
                            <label for="cpf"><strong>CPF:</strong> {{ servidor.cpf }}</label>
                        </div>
                        <div class="form-group">
                            <label for="telefone"><strong>Telefone:</strong> {{ servidor.telefone }}</label>
                        </div>
                        <div class="form-group">
                            <label for="email"><strong>Email:</strong> {{ servidor.email }}</label>
                        </div>
                        <div class="form-group">
                            <label for="data_nascimento"><strong>Data de Nascimento:</strong> {{ servidor.data_nascimento }}
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="logradouro"><strong>Logradouro:</strong> {{ servidor.logradouro }}</label>
                        </div>
                        <div class="form-group">
                            <label for="numero"><strong>Número:</strong> {{ servidor.numero }}</label>
                        </div>
                        <div class="form-group">
                            <label for="zona"><strong>Zona:</strong> {{ servidor.get_zona_display }}</label>
                        </div>
                        <div class="form-group">
                            <label for="bairro"><strong>Bairro/Vila:</strong> {{ servidor.bairro }}</label>
                        </div>
                        <div class="form-group">
                            <label for="estado"><strong>Estado:</strong> {{ servidor.estado }}</label>
                        </div>
                        <div class="form-group">
                            <label for="municipio"><strong>Município:</strong> {{ servidor.municipio }}</label>
                        </div>
                        <div class="form-group">
                            <label for="cep"><strong>CEP:</strong> {{ servidor.cep }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong>Formação</strong></h5>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="escolaridade"><strong>Escolaridade:</strong> {{ servidor.get_escolaridade_display }}
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="formacao"><strong>Formação:</strong> {{ servidor.formacao }}</label>
                        </div>
                        <div class="form-group">
                            <label for="instituicao"><strong>Instituição:</strong> {{ servidor.instituicao }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong>Lotação</strong></h5>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="cargo"><strong>Cargo:</strong> {{ servidor.cargo }}</label>
                        </div>
                        <div class="form-group">
                            <label for="funcao"><strong>Função:</strong> {{ servidor.funcao }}</label>
                        </div>
                        <div class="form-group">
                            <label for="vinculo"><strong>Vínculo:</strong> {{ servidor.get_vinculo_display }}</label>
                        </div>
                        <div class="form-group">
                            <label for="local"><strong>Local:</strong> {{ servidor.get_local_display }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong>Dados Bancários</strong></h5>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="banco"><strong>Banco:</strong> {{ servidor.banco }}</label>
                        </div>
                        <div class="form-group">
                            <label for="agencia"><strong>Agência:</strong> {{ servidor.agencia }}</label>
                        </div>
                        <div class="form-group">
                            <label for="conta"><strong>Conta:</strong> {{ servidor.conta }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong>Dados Adicionais</strong></h5>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="data_admissao"><strong>Data de Admissão:</strong> {{ servidor.data_admissao }}
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="data_inicio"><strong>Data de Inicio:</strong> {{ servidor.data_inicio }}</label>
                        </div>
                        <div class="form-group">
                            <label for="data_saida"><strong>Data de Saida:</strong> {{ servidor.data_saida }}</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-3">
        <button class="btn btn-primary" onclick="gerarPDF()">Gerar PDF</button>
        <a href="{% url 'lista_servidores' %}" class="btn btn-secondary">Voltar</a>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
    <script>
        function gerarPDF() {
            const element = document.querySelector('.container');

            html2pdf()
                .set({
                    margin: 0.5,
                    filename: 'detalhes_servidor.pdf',
                    image: {type: 'jpeg', quality: 0.98},
                    html2canvas: {scale: 4},
                    jsPDF: {unit: 'in', format: 'letter', orientation: 'portrait'}
                })
                .from(element)
                .save();
        }
    </script>
{% endblock %}

sgpapp/templates/sgp/editar_servidor.html
{% extends 'sgp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center">Editar Servidor</h2>
    <div class="container mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border p-4">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sgpapp/templates/sgp/ficha_servidor.html
<!DOCTYPE html>
<html>
<head>
    <title>Ficha do Servidor</title>
    <style>
        /* Seus estilos CSS aqui */
    </style>
</head>
<body>
    <h2 class="text-center">Ficha do Servidor</h2>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Informações Pessoais</h5>
                <table>
                    <tr>
                        <td><strong>Nome:</strong></td>
                        <td>{{ servidor.nome }}</td>
                        <td><strong>Sexo:</strong></td>
                        <td>{{ servidor.sexo }}</td>
                        <td><strong>RG:</strong></td>
                        <td>{{ servidor.rg }}</td>
                        <td><strong>CPF:</strong></td>
                        <td>{{ servidor.cpf }}</td>
                        <td><strong>Telefone:</strong></td>
                        <td>{{ servidor.telefone }}</td>
                    </tr>
                </table>
                <br>
                <h5 class="card-title">Endereço</h5>
                <table>
                    <tr>
                        <td><strong>Logradouro:</strong></td>
                        <td>{{ servidor.logradouro }}</td>
                        <td><strong>Número:</strong></td>
                        <td>{{ servidor.numero }}</td>
                        <td><strong>Zona:</strong></td>
                        <td>{{ servidor.zona }}</td>
                    </tr>
                    <tr>
                        <td><strong>Bairro:</strong></td>
                        <td>{{ servidor.bairro }}</td>
                        <td><strong>Estado:</strong></td>
                        <td>{{ servidor.estado }}</td>
                        <td><strong>Município:</strong></td>
                        <td>{{ servidor.municipio }}</td>
                    </tr>
                    <tr>
                        <td><strong>CEP:</strong></td>
                        <td>{{ servidor.cep }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

sgpapp/templates/sgp/index.html
<title>Página Inicial</title>
{% extends 'sgp/base.html' %}
{% block conteudo %}



{% endblock conteudo %}

sgpapp/templates/sgp/lista_servidores.html
<title>Gerenciar Servidores</title>
{% extends 'sgp/base.html' %}

{% block content %}
    <h2 class="text-center">Lista de Servidores</h2>
    <div class="container mt-5">
        <table class="table">
            <!-- Cabeçalho da tabela -->
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Vínculo</th>
                    <th>Cargo</th>
                    <th>Função</th>
                    <th>Escolaridade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <!-- Corpo da tabela -->
                {% for servidor in servidores %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td class="small">{{ servidor.nome }}</td>
                        <td class="small">{{ servidor.get_vinculo_display }}</td>
                        <td class="small">{{ servidor.cargo }}</td>
                        <td class="small">{{ servidor.funcao }}</td>
                        <td class="small">{{ servidor.get_escolaridade_display }}</td>
                        <td>
                            <a href="{% url 'editar_servidor' servidor.id %}" class="btn btn-primary btn-sm">Editar</a>
                            <a href="{% url 'apagar_servidor' servidor.id %}" class="btn btn-danger btn-sm">Apagar</a>
                            <a href="{% url 'detalhar_servidor' servidor.id %}" class="btn btn-info btn-sm">Detalhar</a>
                        </td>
                    </tr>
                {% endfor %}
                <!-- Rodapé da tabela -->
                <tr>
                    <td colspan="7" class="text-end">Total de registros: {{ total_registros }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}